#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

wmake initialiseU

caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam
restore0Dir

./generateMesh

$(getApplication)/$(getApplication) > log.$(getApplication) 2>&1

#------------------------------------------------------------------------------
