#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

solver=KirchhoffKelvinIntegrator2D
$solver RKDP45 > log.$solver 2>&1
python plotTrajectory.py trajectory

#------------------------------------------------------------------------------
