#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ "$1" = "wmake" ] || [ "$1" = "wclean" ]; then
    wcmd="$1"
    shift
else
    wcmd="wmake"
fi

$wcmd "$@" src/functionObjects/forceContributions
$wcmd "$@" src/addedMass
$wcmd "$@" src/floaterMotion
$wcmd "$@" src/functionObjects/floaterStateWriter
$wcmd "$@" src/functionObjects/sixDoFRigidBodyStateWriter
$wcmd "$@" src/functionObjects/addedMassWriter
$wcmd "$@" src/waveMakerMotionSolver
$wcmd "$@" applications/floatStepper
$wcmd "$@" applications/util/joukowskiTransformPoints
$wcmd "$@" applications/util/floaterInertia
$wcmd "$@" applications/util/KirchhoffKelvinIntegrator2D
$wcmd "$@" applications/util/addedMassCalculator
$wcmd "$@" applications/util/kelvinKirchhoffEquationSolver
$wcmd "$@" applications/util/floaterMotionPotentialFlow