#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam
restore0Dir

# Generate base mesh
runApplication blockMesh

# Set initial free surface
runApplication setFields

# Run case
runApplication $(getApplication)

#PostProcessing Mooringlines - load .pvd from Mooring folder to visualise the mooring lines together
python MooringVisualizationInParaview.py

#------------------------------------------------------------------------------