#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

touch dum.foam constant/CofR
restore0Dir

# Generate base mesh
runApplication blockMesh

# Refine mesh
runApplication -s 1 topoSet -dict system/topoSetDict1
runApplication -s 1 refineMesh -dict system/refineMeshDict1 -overwrite
#runApplication -s 2 topoSet -dict system/topoSetDict2
#runApplication -s 2 refineMesh -dict system/refineMeshDict2 -overwrite

runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch floatingObject

# Calculate mass, centre of mass and moment of inertia
# Uses floatingObject patch and assumes mass density is uniform:
density=500
inside="(100 50 100)"
runApplication surfaceMeshExtract -time 0 -patches floatingObject floater.stl
runApplication surfaceOrient -inside floater.stl "${inside}" floater.stl
runApplication mySurfaceInertia floater.stl -density ${density}
grep -A4 'Entries for floatStepper' log.mySurfaceInertia > tmp
tail -4 tmp > constant/floaterMassAndInertia

# Defining CofR used by forces functionObject in controlDict
grep "centreOfMass" constant/floaterMassAndInertia > constant/CofR
sed -i 's/centreOfMass/CofR/g' constant/CofR
rm tmp floater.stl axes.obj

# Setting CoR in floaterMotionState to calculated CoM
CoR=$(foamDictionary -entry centreOfMass -value constant/floaterMassAndInertia)
foamDictionary -entry centreOfRotation -set "$CoR" 0.orig/uniform/floaterMotionState
foamDictionary -entry centreOfRotation -set "$CoR" 0/uniform/floaterMotionState

# Setting CoM to (0 0 0) relative to CoR in floaterMassAndInertia
foamDictionary -entry centreOfMass -set '( 0 0 0 )' constant/floaterMassAndInertia

# Write mooring file for inclusion in constant/dynamicMeshDict
python3 writeMooringFile.py

# Set initial free surface
runApplication setFields

# Run case
runApplication decomposePar
runParallel $(getApplication)
#runApplication $(getApplication)

#------------------------------------------------------------------------------
