#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam
restore0Dir
cp -pr 0.orig/* 0/

# Generate base mesh
runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel $(getApplication)

# Reconstruct
runApplication reconstructPar

#------------------------------------------------------------------------------
