#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./setCaseParms

(
    cd initUcase
    ./Allrun
)

caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam
restore0Dir

#./generateMesh

cp -r initUcase/constant/polyMesh constant
runApplication mapFields initUcase -sourceTime latestTime -consistent
cp 0.orig/pointDisplacement 0/
rm -rf 0/Phi

# Calculating body mass, centre of mass and inertia
runApplication surfaceMeshExtract -time 0 -patches floatingObject floater.stl
runApplication surfaceOrient -inside floater.stl "(0 0 0)" floater.stl
bodyDensity=$(foamDictionary -entry bodyDensity -value initUcase/constant/bodyParmDict)
runApplication mySurfaceInertia floater.stl -density ${bodyDensity}
grep -A4 'Entries for floatStepper' log.mySurfaceInertia > tmp
tail -4 tmp > constant/floaterMassAndInertia
rm tmp axes.obj

runApplication $(getApplication)

#------------------------------------------------------------------------------
