#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

caseName=$(basename $(dirname $(readlink -f "$0")))
touch ${caseName}.foam
restore0Dir

#mv dynamicCode.old dynamicCode
# Meshing
./generateMesh > log.generateMesh 2>&1
runApplication $(getApplication)

#------------------------------------------------------------------------------
