#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

python writeMeshParmFile.py
blockMesh
cp system/mirrorMeshDict.X system/mirrorMeshDict
mirrorMesh -overwrite
cp system/mirrorMeshDict.Y system/mirrorMeshDict
mirrorMesh -overwrite
autoPatch 45 -overwrite
topoSet
createPatch -overwrite
sed -i '0,/auto0.*$/s//floatingObject/' constant/polyMesh/boundary
sed -i '0,/auto3.*$/s//rim/' constant/polyMesh/boundary
joukowskiTransformPoints -joukowski 0.5
# transformPoints -rollPitchYaw '(0 0 45))'
# transformPoints -translate '(1 1 0)'

#transformPoints -rollPitchYaw '(0 0 30))'
#transformPoints -translate '(1 1 0)'

# transformPoints -rollPitchYaw '(0 0 45))'
# transformPoints -translate '(0 0 0)'
