#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase0
rm -rf floater.stl 0 trajectory forceAndTorque KKtrajectory
rm rigidBodyMotionStateInput
#------------------------------------------------------------------------------
