#!/bin/sh

# Parameters to vary
bodyDensity=0.8
bodyEccentricity=0

vx0=0
vy0=0
omega0=0

# Making dictionary used for theoretical Kirchoff Kelvin solution
dict=bodyDict
foamDictionary -disableFunctionEntries -entry rhob -set "$bodyDensity" $dict
foamDictionary -disableFunctionEntries -entry a -set "$bodyEccentricity" $dict
foamDictionary -disableFunctionEntries -entry vx0 -set "$vx0" $dict
foamDictionary -disableFunctionEntries -entry vy0 -set "$vy0" $dict
foamDictionary -disableFunctionEntries -entry omega0 -set "$omega0" $dict
tend=$(foamDictionary -entry endTime -value system/controlDict)
foamDictionary -disableFunctionEntries -entry tend -set "$tend" $dict

KirchhoffKelvinIntegrator2D RKDP45 > log.KirchhoffKelvinIntegrator2D

# Initial body state dictionary used by floatStepper
dict=0/uniform/floaters
foamDictionary -disableFunctionEntries -entry body.velocity -set "( $vx0 $vy0 0)" $dict
foamDictionary -disableFunctionEntries -entry body.omega -set "( 0 0 $omega0 )" $dict
acceleration=$(foamDictionary -entry acceleration -value rigidBodyMotionStateInput)
foamDictionary -disableFunctionEntries -entry body.acceleration -set "$acceleration" $dict
domegadt=$(foamDictionary -entry domegadt -value rigidBodyMotionStateInput)
foamDictionary -disableFunctionEntries -entry body.domegadt -set "$domegadt" $dict
