#!/bin/bash

#Make a sequence of copies of baseCase and change one or more parameters in the
#setup files of each case

#Settings

baseCase=${1:-baseCase}

scanDir=benchmarks

if [ ! -d "$scanDir" ];
then
    mkdir $scanDir
    cp -r $baseCase $scanDir
fi

cd $scanDir

parm1File="constant/waveProperties"
parm2File="constant/waveProperties"
parm1Name="waveHeight"
parm2Name="wavePeriod"
parm1Range=(0.04 0.10)
parm2Range=(1.2 1.2)
#parm1Range=(400)
#parm2Range=(120)

#parm3File="system/controlDict"
#parm3Name=maxCo
#parm3Range=(0.1 0.2 0.5 0.05)
#parm3Range=(0.2)

##########################

echo "=========================================" >> README
echo "Parameter scan generated with $(basename "$0")" >> README
echo "Date: " $(date) >> README
echo "Base case: $baseCase" >> README
echo "Parameters: $parm1Name, $parm2Name" >> README
echo "=========================================" >> README
echo "Case    $parm1Name    $parm2Name" >> README

#for m in ${!parm3Range[*]}
#do
#    parm3=${parm3Range[$m]}

    for n in ${!parm1Range[*]}
    do
        parm1=${parm1Range[$n]}
        parm2=${parm2Range[$n]}
#        caseName=$(printf "%03d\n" "$n")
        caseName=$parm1Name$parm1$parm2Name$parm2
        if [ "${1}" = "run" ];
        then
            cd ${caseName}
            ./Allrun &
            cd ..
        elif [ ! -d "$caseName" ];
        then
            cp -r ../$baseCase $caseName
            foamDictionary  -disableFunctionEntries -entry inlet."${parm1Name}" -set "${parm1}" ${caseName}/${parm1File}
            foamDictionary  -disableFunctionEntries -entry inlet."${parm2Name}" -set "${parm2}" ${caseName}/${parm2File}
            echo "$caseName:    $parm1    $parm2" >> README
        else
            echo "Directory $caseName already exists - not recreated."
        fi
    done
#done

echo "=========================================" >> README
