#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

python3 writeMeshParmFile.py
runApplication blockMesh
cp system/mirrorMeshDict.X system/mirrorMeshDict
runApplication mirrorMesh -overwrite
mv log.mirrorMesh log.mirrorMeshX
cp system/mirrorMeshDict.Y system/mirrorMeshDict
runApplication mirrorMesh -overwrite
runApplication autoPatch 45 -overwrite
runApplication topoSet
runApplication createPatch -overwrite
sed -i '0,/auto0.*$/s//floatingObject/' constant/polyMesh/boundary
sed -i '0,/auto1.*$/s//rim/' constant/polyMesh/boundary
